name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject Firebase Secrets
        run: |
          echo "const firebaseConfig = {
            apiKey: '${{ secrets.FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.FIREBASE_APP_ID }}',
            measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
          };\n\nfirebase.initializeApp(firebaseConfig);" > js/firebase-config.js

      - name: Deploy Website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Change if deploying to a different branch
          folder: .  # Deploy the entire repository
